spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

# Optional, for fallback logging if config server fails
logging:
  level:
    root: INFO

server:
  port: 8085
